@startuml Clinic Management 

class Doctor{
    -id
    -name 
    -address
    -phone_number
    -license_number
    -expertise
    -schedule: Schedule
    +set_schedule()
    +get_schedule()
}

class Patient{
    -id
    -name
    -address
    -phone_number
    -treatment: Diagnosis
    -schedule: Schedule
    +get_diagnosis()
    +set_schedule()
    +get_schedule()
}

class Diagnosis{
    -medicine
    -dose
    -treatment_length
    -lab_test
    +get_lab_test(id, description, location, date)
}

class Schedule{
    -days
    -hours 
    +get_calender()
}

Doctor o-- Schedule
Doctor o-- Patient
Patient o-- Schedule
Patient +-- Diagnosis

@enduml